### ISSUE TITLE
Document-related issues

### ISSUE THREAD

**Issue by fuyu-quant** [auto-res/researchgraph#314]
- Once the name of the OSS is officially decided, acquire the domain.
- Japanese language support
- Automatic deployment using github actions
```
name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # 手動で認証するため

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install
        working-directory: docs

      - name: Build Docusaurus site
        run: yarn build
        working-directory: docs

      - name: Deploy to GitHub Pages
        env:
          GIT_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          yarn deploy
        working-directory: docs

```
